name: Build IPA for Esign

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build Btn Launcher IPA
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Java 8 (required cho build)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install dependencies
        run: |
          brew update
          brew install make cmake wget coreutils ldid

      - name: Build IPA (dùng cho Esign/AltStore/SideStore)
        run: |
          export PATH="/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/bin:/usr/local/bin:$JAVA_HOME/bin:$PATH"
          export SDKPATH=$(xcrun --sdk iphoneos --show-sdk-path)
          export BOOTJDK=$JAVA_HOME/bin
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2

      - name: Build TIPA (dùng cho TrollStore - JIT tốt hơn)
        run: |
          export PATH="/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/bin:/usr/local/bin:$JAVA_HOME/bin:$PATH"
          export SDKPATH=$(xcrun --sdk iphoneos --show-sdk-path)
          export BOOTJDK=$JAVA_HOME/bin
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=2 TROLLSTORE_JIT_ENT=1

      - name: Upload IPA - tải về import Esign
        uses: actions/upload-artifact@main
        with:
          name: BtnLauncher.ipa
          path: artifacts/com.btnlauncher.ios-*-ios.ipa

      - name: Upload TIPA - TrollStore
        uses: actions/upload-artifact@main
        with:
          name: BtnLauncher.tipa
          path: artifacts/com.btnlauncher.ios-*-ios-trollstore.tipa
